version: '3.8'

services:
  db:
    container_name: $TYPEORM_HOST
    image: postgis/postgis:15-3.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgressql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}